EE_LIB = ../libexceptionman.a
EE_OBJS += exphandler.o exceptions.o

all: $(EE_LIB)
clean:
	rm -rf $(EE_LIB) $(EE_OBJS)

include $(PS2SDK)/samples/Makefile.pref
include $(PS2SDK)/samples/Makefile.eeglobal